name: trailerhive
description: An app which lets you watch trailers and save movies easily

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mobx_codegen: ^2.0.5+2
  flutter_svg: 
  auto_size_text: 
  intl: 
  http: ^0.13.5
  strings: ^0.2.2
  youtube_player_flutter: ^8.1.2
  sembast: ^3.1.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  freezed: ^2.0.2
  flutter_gen_runner:
  build: ^2.3.0
  build_runner: ^2.1.10
  retrofit_generator: ^4.0.1
  injectable_generator:
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
  flutter_native_splash: ^2.2.5

flutter_gen:
  output: lib/core/gen/
  flutter_svg: true


flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/th_launcher_icon.png"
  image_path_android: "assets/images/th_launcher_icon.png"


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/th_launcher_icon.png

flutter:
  uses-material-design: true

  # assets:
  #   - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 200
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lato-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Lato-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 800
